name: Bands

on:
  push:
    branches:
      - '**/**'
jobs:
  CI:
    uses: ./.github/workflows/dotnet-ci-template.yml
    with:
      # config-path: .github/labeler.yml
      ENV: "dev"
      WEBAPP_NAME: "dotnet"
      DOTNET_VERSION: "6.0.x"
      SOLUTION_FILE_PATH: "./"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
