name: CD Pipeline Template

on:
  workflow_call:
    inputs:
      ENV: 
        type: string
      WEBAPP_NAME:
        required: true
        type: string  
      RELEASE_ARTIFACT:
        type: string
      RUN_ID:
        type: string
    secrets:
      token:
        required: true

jobs:
  DotNet_Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download The Release Artifact
      uses: dawidd6/action-download-artifact@v2
      id: download
      with:
        run_id: ${{ inputs.RUN_ID }}
        name: ${{ inputs.RELEASE_ARTIFACT }}
        path: /tmp
    - name: Configure AWS Credentials 
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
          aws-region: ap-southeast-1
          role-to-assume: arn:aws:iam::914917921893:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC

    - name: Deploy
      run: echo "Deploying to Lambda using Pulumi Scripts " ${{steps.download.outputs.download-path}}
    - name: List available pulumi stacks
      working-directory: "./infra"
      run: pulumi stack ls
      env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    - name: List available pulumi stacks
      working-directory: "./infra"
      run: pulumi config set RELEASE_ARTIFACT ${{ steps.download.outputs.download-path }}
      env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    - name: lambda pulumi stack deploy
      uses: pulumi/actions@v4
      with:
          command: up
          work-dir: "./infra"
          stack-name: ${{inputs.ENV}}
          upsert: true
      env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

