name: Manual Bands Artifact Deploy

on:
  workflow_dispatch:

jobs:
  CD:
    uses: ./.github/workflows/dotnet-cd-template.yml
    with:
      # config-path: .github/labeler.yml
      ENV: "dev"
      RELEASE_ARTIFACT: "dotnet-1.0.5-6765744570-06-11-2023-025849"
      RUN_ID: "6765744570"
      WEBAPP_NAME: "dotnet"
      AWS_REGION: 'ap-southeast-1'
      ACCOUNT_ID: "914917921893"
    secrets: inherit
