name: CD Pipeline Template

on:
  workflow_call:
    inputs:
      ENV: 
        type: string
      WEBAPP_NAME:
        required: true
        type: string  
      RELEASE_ARTIFACT:
        type: string
      RUN_ID:
        type: string
      AWS_REGION:
        type: string
      ACCOUNT_ID: 
        type: string
   
permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout
jobs:
  DotNet_Deploy:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create stage directory for the artifact
      run: mkdir /tmp/${{inputs.WEBAPP_NAME}}
    - name: Download The Release Artifact
      uses: dawidd6/action-download-artifact@v2
      id: download
      with:
        run_id: ${{ inputs.RUN_ID }}
        name: ${{ inputs.RELEASE_ARTIFACT }}
        path: /tmp/${{inputs.WEBAPP_NAME}}
    - name: Configure AWS Credentials 
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
          aws-region: ap-southeast-1
          role-to-assume: arn:aws:iam::914917921893:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
    - name: Sts GetCallerIdentity
      run: |
            aws sts get-caller-identity
    - name: Deploy
      run: echo "Deploying to Lambda using Pulumi Scripts " ${{steps.download.outputs.download-path}}
    - name: Setup npm for pulumi
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install npm dependencies
      working-directory: "infra"
      run: npm install
    - name: List available pulumi stacks
      working-directory: "infra"
      run: pulumi stack ls
      env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    - name: Init Pulumi Stack
      working-directory: "infra"
      run: pulumi stack select ${{inputs.ENV}} -c
      env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    - name: Set config for stack
      working-directory: "infra"
      run: |
        pulumi config set RELEASE_ARTIFACT ${{ steps.download.outputs.download-path }}
        pulumi config set AWS_REGION ${{ inputs.AWS_REGION}}
        pulumi config set ACCOUNT_ID ${{ inputs.ACCOUNT_ID}}
        pulumi config set WEBAPP_NAME ${{ inputs.WEBAPP_NAME}}
        
      env:
              PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        
    - name: lambda pulumi stack deploy
      uses: pulumi/actions@v4
      with:
          command: up
          work-dir: "infra"
          stack-name: ${{inputs.ENV}}
      env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

