name: Manual Bands Artifact Deploy

on:
  workflow_dispatch:

jobs:
  CD:
    uses: ./.github/workflows/dotnet-cd-template.yml
    with:
      # config-path: .github/labeler.yml
      ENV: "dev"
      RELEASE_ARTIFACT: "dotnet-1.0.5-6755678908-04-11-2023-152404"
      WEBAPP_NAME: "dotnet"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}